"""Initial setup with genres

Revision ID: de34c2cd0d9a
Revises: 
Create Date: 2026-06-01 20:34:05.179248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de34c2cd0d9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(length=512), nullable=False),
    sa.Column('title_ru', sa.String(length=512), nullable=True),
    sa.Column('poster_path', sa.String(length=512), nullable=True),
    sa.Column('collection_name', sa.String(length=256), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genres', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_cache_id'), 'movies_cache', ['id'], unique=False)
    op.create_index(op.f('ix_movies_cache_title_en'), 'movies_cache', ['title_en'], unique=False)
    op.create_index(op.f('ix_movies_cache_tmdb_id'), 'movies_cache', ['tmdb_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('min_rating', sa.Float(), nullable=False),
    sa.Column('min_year', sa.Integer(), nullable=False),
    sa.Column('watched', sa.Text(), nullable=False),
    sa.Column('liked_movies', sa.Text(), nullable=False),
    sa.Column('disliked_movies', sa.Text(), nullable=False),
    sa.Column('liked_genres', sa.Text(), nullable=False),
    sa.Column('disliked_genres', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('user_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies_cache.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='u_user_movie')
    )
    op.create_index(op.f('ix_user_collection_id'), 'user_collection', ['id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=16), nullable=False),
    sa.Column('genre_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies_cache.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='u_user_feedback_movie')
    )
    op.create_index(op.f('ix_user_feedback_id'), 'user_feedback', ['id'], unique=False)
    op.create_table('user_genre_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'genre_id', 'feedback_type', name='u_user_genre_feedback')
    )
    op.create_index(op.f('ix_user_genre_preferences_genre_id'), 'user_genre_preferences', ['genre_id'], unique=False)
    op.create_index(op.f('ix_user_genre_preferences_id'), 'user_genre_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_genre_preferences_id'), table_name='user_genre_preferences')
    op.drop_index(op.f('ix_user_genre_preferences_genre_id'), table_name='user_genre_preferences')
    op.drop_table('user_genre_preferences')
    op.drop_index(op.f('ix_user_feedback_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_user_collection_id'), table_name='user_collection')
    op.drop_table('user_collection')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_movies_cache_tmdb_id'), table_name='movies_cache')
    op.drop_index(op.f('ix_movies_cache_title_en'), table_name='movies_cache')
    op.drop_index(op.f('ix_movies_cache_id'), table_name='movies_cache')
    op.drop_table('movies_cache')
    # ### end Alembic commands ###
